# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d8ff42984e9cd615a6826f0c878ce4d9ec9b5407cddacf3c74855d466ff06e5a1328b39b9d8f295c9ddd066dac73fb375efd98ceba6c235e47219f711e40dd8c

test:
  secret_key_base: a830060376839753ce5298bf455a839622ec400567c4da672179a79dafc6fc3c30483c645b8c7cc77aee467a827991ed2b6e19431f9243b7f375bc5dc246ca29

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
